"""empty message

Revision ID: bc4015952652
Revises: 
Create Date: 2023-02-13 05:42:19.264945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4015952652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'h_endpoints',
        sa.Column('h_endpoint_id', sa.Integer(), nullable=False),
        sa.Column('h_endpoint', sa.Text(), nullable=False),
        sa.Column('h_endpoint_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('h_endpoint_id'),
        sa.UniqueConstraint('h_endpoint')
    )
    op.create_table(
        'h_sources',
        sa.Column('h_source_id', sa.Integer(), nullable=False),
        sa.Column('h_source', sa.Text(), nullable=False),
        sa.Column('h_source_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('h_source_id'),
        sa.UniqueConstraint('h_source')
    )
    op.create_table(
        'l_sources_endpoints',
        sa.Column('l_source_endpoint_id', sa.Integer(), nullable=False),
        sa.Column('h_source_id', sa.Integer(), nullable=False),
        sa.Column('h_endpoint_id', sa.Integer(), nullable=False),
        sa.Column('l_source_endpoint_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['h_endpoint_id'], ['h_endpoints.h_endpoint_id'], ),
        sa.ForeignKeyConstraint(['h_source_id'], ['h_sources.h_source_id'], ),
        sa.PrimaryKeyConstraint('l_source_endpoint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l_sources_endpoints')
    op.drop_table('h_sources')
    op.drop_table('h_endpoints')
    # ### end Alembic commands ###